import { useState } from "react";
import { Check, MoreHorizontal, Save } from "lucide-react";
import { Button } from "@workspace/s1/components/ui/button";
import { Input } from "@workspace/s1/components/ui/input";
import { Shell, Mono, PageLabel, Rule, Tag, ingredientRows } from "./_shared";

export function FormulaLab() {
  const [selected, setSelected] = useState(4);
  return <Shell mode="lab"><div className="bg-foreground text-background px-5 py-8 lg:px-12"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-current/15 pb-7"><div><a href="#/matiere/FormulaLibrary" className="font-mono text-[9px] uppercase tracking-[.18em] text-background/60">← Formula library</a><h1 className="mt-5 font-display text-6xl tracking-[-.05em]">Lait Vert 0.2</h1><p className="mt-3 text-sm text-background/65">Green · violet leaf · milky skin · transparent</p></div><div className="flex gap-2"><Button variant="outline" className="rounded-none"><MoreHorizontal size={14} /></Button><Button className="rounded-none"><Save size={13} /> Save revision</Button></div></header>
    <div className="grid gap-px border-b border-border sm:grid-cols-4">{[["Project","Lait Vert"],["Revision","02 / active"],["Concentration","18.00%"],["Total batch","10.000 g"]].map(x => <div key={x[0]} className="bg-foreground px-4 py-4"><PageLabel>{x[0]}</PageLabel><p className="mt-2 font-mono text-xs">{x[1]}</p></div>)}</div>
    <section className="mt-8 grid gap-8 lg:grid-cols-[1fr_280px]"><div className="overflow-x-auto border-t border-border bg-foreground"><table className="w-full min-w-[780px] border-collapse text-left"><thead><tr className="border-b border-border"><th className="px-4 py-3"><Mono>Material</Mono></th><th className="px-3"><Mono>%</Mono></th><th className="px-3"><Mono>Weight g</Mono></th><th className="px-3"><Mono>Dilution</Mono></th><th className="px-3"><Mono>Role</Mono></th><th className="px-3"><Mono>Notes / flags</Mono></th></tr></thead><tbody>{ingredientRows.map((r,i) => <tr key={r[0]} onClick={() => setSelected(i)} className={`cursor-pointer border-b border-border transition-colors ${selected === i ? "bg-accent/15" : "hover:bg-muted"}`}><td className="px-4 py-4 text-sm font-medium">{r[0]}{i === 4 && <Tag className="ml-2">focus</Tag>}</td><td className="px-3 font-mono text-xs">{r[1]}</td><td className="px-3 font-mono text-xs">{r[2]}</td><td className="px-3 font-mono text-xs text-muted-foreground">{r[3]}</td><td className="px-3 font-mono text-[10px] uppercase text-muted-foreground">{r[4]}</td><td className="px-3 text-xs text-muted-foreground">{r[5]}</td></tr>)}</tbody></table></div><aside className="space-y-5"><div className="border-t-2 border-current bg-foreground p-5"><PageLabel>Blend total</PageLabel><p className="mt-3 font-display text-5xl">54.43%</p><p className="mt-2 text-xs text-muted-foreground">of 18.00% target · 9 materials shown</p><div className="mt-5 h-1 bg-border"><div className="h-full w-[72%] bg-current" /></div></div><div className="border-t border-current/15 pt-5"><PageLabel>Technical flags</PageLabel><div className="mt-4 space-y-3"><p className="flex items-center gap-2 text-xs"><Check size={13} /> All CAS linked</p><p className="flex items-center gap-2 text-xs"><Check size={13} /> Cat 4 within limits</p><p className="flex items-center gap-2 text-xs text-accent-foreground">! Cashmeran warming base</p></div></div><div className="border-t border-current/15 pt-5"><PageLabel>Bench note</PageLabel><Input className="mt-3 rounded-none bg-foreground" defaultValue="Keep opening cold; reduce warmth." /></div></aside></section>
    <Rule>Revision notes</Rule><section className="grid gap-8 sm:grid-cols-3"><div><Mono>02 · today</Mono><p className="mt-3 text-sm leading-6">Violet leaf 2.10 → 2.40%. Stemone 0.20 → 0.35%.</p></div><div><Mono>01 · 26 Feb</Mono><p className="mt-3 text-sm leading-6 text-muted-foreground">Moved the green accord above the floral body.</p></div><div><Mono>Direction</Mono><p className="mt-3 text-sm leading-6 text-muted-foreground">Push the green opening without increasing density.</p></div></section>
  </div></Shell>;
}