import { Search, ArrowRight } from "lucide-react";
import { Input } from "@workspace/s1/components/ui/input";
import { Button } from "@workspace/s1/components/ui/button";
import { Shell, Mono, PageLabel, formulas, Tag } from "./_shared";

export function FormulaLibrary() {
  return <Shell mode="lab"><div className="bg-foreground text-background px-5 py-10 lg:px-12"><header className="flex flex-col gap-6 border-b border-current/15 pb-8 sm:flex-row sm:items-end sm:justify-between"><div><PageLabel>Laboratory / archive</PageLabel><h1 className="mt-3 font-display text-6xl tracking-[-.05em]">Formula library</h1><p className="mt-4 max-w-lg text-sm text-background/65">A living archive of trials, revisions and sensory readings across the studio.</p></div><Button variant="outline" className="rounded-none"><span>New formula</span><ArrowRight size={13} /></Button></header>
    <div className="flex flex-col gap-4 border-b border-border py-5 sm:flex-row"><div className="relative flex-1"><Search size={14} className="absolute left-3 top-3 text-muted-foreground" /><Input className="rounded-none pl-9" placeholder="Search formulas, projects, materials" /></div><Tag>8 records</Tag><Tag>Updated recently</Tag></div>
    <div className="mt-8 overflow-x-auto border-t border-current/15"><table className="w-full min-w-[900px] border-collapse text-left"><thead><tr className="border-b border-current/15"><th className="py-3 pr-5"><Mono>Name</Mono></th><th><Mono>Project</Mono></th><th><Mono>Materials</Mono></th><th><Mono>Last edited</Mono></th><th><Mono>Last evaluated</Mono></th><th><Mono>Direction</Mono></th></tr></thead><tbody>{formulas.map((f,i) => <tr key={f[0]} className="group border-b border-current/15 transition-colors hover:bg-background/10"><td className="py-5 pr-5"><a href="#/matiere/FormulaLab" className="font-medium">{f[0]}<span className="mt-1 block font-mono text-[9px] uppercase tracking-[.15em] text-muted-foreground">{f[1]}</span></a></td><td className="font-mono text-xs text-muted-foreground">{i < 4 ? "LAIT VERT" : i < 6 ? "STUDIES" : "ARCHIVE"}</td><td className="font-mono text-xs">{f[2]}</td><td className="font-mono text-xs text-muted-foreground">{f[4]}</td><td className="font-mono text-xs text-muted-foreground">{f[5]}</td><td className="max-w-[230px] text-xs text-muted-foreground">{f[3]}</td></tr>)}</tbody></table></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="border-t-2 border-current bg-foreground p-4"><PageLabel>Active project</PageLabel><p className="mt-3 font-display text-3xl">Lait Vert</p><Mono className="mt-2 block text-muted-foreground">4 formula revisions</Mono></div><div className="border-t border-current/15 p-4"><PageLabel>Recent evaluation</PageLabel><p className="mt-3 text-sm">Lait Vert 0.2 · 4 hours</p><Mono className="mt-2 block text-muted-foreground">28 Feb 2024</Mono></div><div className="border-t border-current/15 p-4"><PageLabel>Archive status</PageLabel><p className="mt-3 text-sm">All formula records indexed</p><Mono className="mt-2 block text-muted-foreground">Last sync · today</Mono></div></div>
  </div></Shell>;
}