import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { Shell, Image, Mono, PageLabel, Rule } from "./_shared";

export function MaterialDetail() {
  const [open, setOpen] = useState(false);
  return <Shell><div className="bg-foreground text-background"><section className="relative min-h-[470px] overflow-hidden bg-background text-foreground"><Image src="leaves.jpg" alt="" className="absolute inset-0 h-full w-full opacity-60" /><div className="absolute inset-0 bg-background/35" /><div className="relative flex min-h-[470px] flex-col justify-end px-6 py-12 lg:px-16"><PageLabel>Natural / green / specimen 014</PageLabel><h1 className="mt-5 max-w-4xl font-display text-7xl leading-[.8] tracking-[-.06em] sm:text-9xl">Violet Leaf<br />Absolute</h1><p className="mt-7 max-w-md text-lg leading-7 text-foreground/80">Wet foliage. Crushed stems. Metallic green. Cold, dark and distinctly vegetal.</p></div></section>
    <div className="px-6 py-12 lg:px-16"><div className="grid gap-10 lg:grid-cols-[1fr_1fr]"><div><PageLabel>Sensory portrait</PageLabel><p className="mt-5 max-w-lg font-display text-4xl leading-tight">The first impression is almost electrical — a green edge that feels wet, cold and close to the skin.</p><p className="mt-6 max-w-lg text-sm leading-7 text-muted-foreground">In Lait Vert, violet leaf carries the composition away from cosmetic green and toward something architectural: stem, glass, shadow.</p></div><div className="grid grid-cols-2 border-t border-border">{[["Type","Natural absolute"],["Source","France · leaf"],["Odor family","Green / metallic"],["Strength","High impact"],["Typical dosage","0.05–0.80%"],["CAS","8024-00-8"],["IFRA Cat 4","0.80%"],["Supplier","Robertet"]].map(x => <div key={x[0]} className="border-b border-border px-3 py-4 first:pl-0"><Mono className="text-muted-foreground">{x[0]}</Mono><p className="mt-2 text-sm">{x[1]}</p></div>)}</div></div>
      <Rule>Technical disclosure</Rule><div className="max-w-3xl border-t border-border"><button onClick={() => setOpen(!open)} className="flex w-full items-center justify-between py-5 text-left"><PageLabel>Composition, regulation and use</PageLabel><ChevronDown size={15} className={open ? "rotate-180" : ""} /></button>{open && <div className="grid gap-8 border-t border-border pb-7 pt-6 sm:grid-cols-2"><div><Mono>CAS / INCI</Mono><p className="mt-3 text-sm leading-6">8024-00-8 · Viola odorata leaf extract</p></div><div><Mono>Allergen notes</Mono><p className="mt-3 text-sm leading-6">Contains naturally occurring traces of linalool and methyl salicylate.</p></div><div><Mono>Handling</Mono><p className="mt-3 text-sm leading-6">Dilute to 10% before evaluation. Allow 48 hours for the green edge to settle.</p></div><div><Mono>Stock</Mono><p className="mt-3 text-sm leading-6">In stock · 34.2 g remaining</p></div></div>}</div>
      <Rule>In the studio</Rule><div className="grid gap-8 sm:grid-cols-3"><a href="#/matiere/ProjectOverview" className="border-t border-border pt-4"><PageLabel>Project</PageLabel><p className="mt-3 font-display text-3xl">Lait Vert</p><Mono className="mt-3 block text-muted-foreground">2.40% in Mod 02</Mono></a><a href="#/matiere/FormulaLab" className="border-t border-border pt-4"><PageLabel>Formula</PageLabel><p className="mt-3 font-display text-3xl">Lait Vert 0.2</p><Mono className="mt-3 block text-muted-foreground">top / anchor</Mono></a><div className="border-t border-border pt-4"><PageLabel>Personal note</PageLabel><p className="mt-3 text-sm leading-6">Use with galbanum for sharper stem, then let Hedione open the space.</p></div></div>
    </div></div></Shell>;
}