import { ArrowRight, Plus } from "lucide-react";
import { NotebookEntry } from "@workspace/s1/components/ui/notebook-entry";
import { Button } from "@workspace/s1/components/ui/button";
import { Shell, Image, Mono, PageLabel, Rule, Tag, materials } from "./_shared";

export function ProjectOverview() {
  return <Shell>
    <section className="bg-background text-foreground"><div className="grid min-h-[390px] items-end gap-10 px-6 py-12 lg:grid-cols-[1.15fr_.85fr] lg:px-16"><div><PageLabel>Project / active / mod 02</PageLabel><h1 className="mt-5 font-display text-7xl leading-[.8] tracking-[-.06em] sm:text-9xl">Lait Vert</h1><p className="mt-7 max-w-lg text-sm leading-6 text-foreground/70">A study in green translucency, wet foliage and the soft mineral warmth of skin.</p></div><Image src="leaves.jpg" alt="Wet green leaves" className="h-64 w-full mix-blend-screen opacity-80 lg:h-72" /></div></section>
    <div className="bg-foreground text-background px-6 py-12 lg:px-16"><div className="flex flex-wrap gap-2 border-b border-current/15 pb-5"><Tag>Current direction</Tag><Mono>Green · transparent floral · milky skin</Mono><span className="mx-2 text-background/40">/</span><Mono>Last touched today</Mono></div>
      <section className="grid gap-12 py-14 lg:grid-cols-[.7fr_1.3fr]"><div><PageLabel>Current direction</PageLabel><h2 className="mt-4 max-w-sm font-display text-5xl leading-[.9] tracking-[-.04em]">Not botanical.<br />Architectural green.</h2><p className="mt-6 max-w-sm text-sm leading-7 text-muted-foreground">Cold vegetal opening, translucent floral diffusion, mineral skin and pale dry woods. Keep the composition quiet, never cosmetic.</p></div><div className="grid gap-8 sm:grid-cols-2"><div><PageLabel>Current mod</PageLabel><p className="mt-3 font-display text-6xl">02</p><p className="mt-3 text-sm text-muted-foreground">The green opening is clearer. Violet leaf now arrives wet and metallic before the floral air lifts it.</p></div><div><PageLabel>Key materials</PageLabel><div className="mt-3 space-y-3">{materials.slice(0,4).map(m => <a href="#/matiere/MaterialDetail" key={m[0]} className="flex items-center justify-between border-b border-border pb-3 text-sm hover:text-muted-foreground">{m[0]}<ArrowRight size={12} /></a>)}</div></div></div></section>
      <Rule>Working notebook</Rule>
      <section className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><PageLabel>Latest evaluation</PageLabel><p className="mt-4 font-display text-3xl leading-tight">The smell of a greenhouse after everyone has left.</p><Button variant="outline" className="mt-7 rounded-none">Open evaluation <ArrowRight size={13} /></Button></div><div><NotebookEntry label="15 min" date="28 Feb 2024" body="The opening is finally green enough. Violet leaf reads wet rather than cosmetic." timeline /><NotebookEntry label="1 hour" date="28 Feb 2024" body="The transition into Hedione is beautiful but slightly too soft." timeline /><NotebookEntry label="4 hours" date="28 Feb 2024" body="Cashmeran may still be warming the base too much. Explore a colder woody structure." timeline /></div></section>
      <Rule>Inspiration / source material</Rule>
      <section className="grid gap-4 sm:grid-cols-3"><Image src="mood-fresh.jpg" alt="" className="h-56 w-full" /><Image src="mood-clean.jpg" alt="" className="h-56 w-full" /><div className="flex h-56 flex-col justify-end border-t border-border p-4"><PageLabel>Direction note</PageLabel><p className="mt-4 font-display text-2xl">Cold light on wet stems.</p><a href="#/matiere/Inspiration" className="mt-5 font-mono text-[9px] uppercase tracking-[.18em]">Open moodboard <ArrowRight size={11} className="ml-1 inline" /></a></div></section>
      <div className="mt-14 flex items-center justify-between border-t border-border pt-5"><Mono>Project record · LV-2024-02</Mono><Button variant="ghost" className="rounded-none"><Plus size={13} /> Add note</Button></div>
    </div>
  </Shell>;
}