// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sillage-atelier-copy-K9nq0Ea1/SillageAtelierCopyK9nq0Ea1.tsx": () => import("../components/mockups/sillage-atelier-copy-K9nq0Ea1/SillageAtelierCopyK9nq0Ea1.tsx"),
  "./components/mockups/sillage-atelier-copy-K9nq0Ea1/SillageAtelierNoir.tsx": () => import("../components/mockups/sillage-atelier-copy-K9nq0Ea1/SillageAtelierNoir.tsx"),
  "./components/mockups/sillage-atelier-copy-K9nq0Ea1/SillageWorkbenchMobile.tsx": () => import("../components/mockups/sillage-atelier-copy-K9nq0Ea1/SillageWorkbenchMobile.tsx"),
  "./components/mockups/sillage-atelier-copy-YVL21Ywa/SillageAtelierCopyYVL21Ywa.tsx": () => import("../components/mockups/sillage-atelier-copy-YVL21Ywa/SillageAtelierCopyYVL21Ywa.tsx"),
  "./components/mockups/sillage-atelier-copy-YVL21Ywa/SillageAtelierNoir.tsx": () => import("../components/mockups/sillage-atelier-copy-YVL21Ywa/SillageAtelierNoir.tsx"),
  "./components/mockups/sillage-atelier-copy-YVL21Ywa/SillageWorkbenchMobile.tsx": () => import("../components/mockups/sillage-atelier-copy-YVL21Ywa/SillageWorkbenchMobile.tsx"),
  "./components/mockups/sillage-atelier/SillageAtelierMobile.tsx": () => import("../components/mockups/sillage-atelier/SillageAtelierMobile.tsx"),
  "./components/mockups/sillage-atelier/SillageAtelierNoir.tsx": () => import("../components/mockups/sillage-atelier/SillageAtelierNoir.tsx"),
  "./components/mockups/sillage-atelier/SillageWorkbenchMobile.tsx": () => import("../components/mockups/sillage-atelier/SillageWorkbenchMobile.tsx"),
  "./components/mockups/sillage-chat/ChatSplitPanelLayout.tsx": () => import("../components/mockups/sillage-chat/ChatSplitPanelLayout.tsx"),
  "./components/mockups/sillage-chat/ChatThreadedLayout.tsx": () => import("../components/mockups/sillage-chat/ChatThreadedLayout.tsx"),
  "./components/mockups/templates/SwissLearningApp-Q_1eba/App.tsx": () => import("../components/mockups/templates/SwissLearningApp-Q_1eba/App.tsx")
};
